CFP/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('misCursos', views.misCursos, name='misCursos'),

    #Localidades
    path('localidadNueva', views.localidadNueva, name='localidadNueva'),
    path('localidades', views.localidades, name='localidades'),
    path('localidadEditar/<int:idLocalidad>', views.localidadEditar, name='localidadEditar'),
    path('localidadBorrar/<int:idLocalidad>', views.localidadBorrar, name='localidadBorrar'),

    #Centros De Formacion
    path('centroNuevo', views.centroNuevo, name='centroNuevo'),
    path('centros', views.centros, name='centros'),
    path('centrosEditar/<int:idCentro>', views.centroEditar, name='centrosEditar'),

    #Cursos
    path('cursoNuevo', views.cursoNuevo, name='cursoNuevo'),
    path('cursos', views.cursoLista, name='cursos'),
    path('cursosInfo', views.cursoInfo, name='cursosInfo'),
    path('cursoEditar/<int:idCurso>', views.cursoEditar, name='cursoEditar'),
    path('inscCurso/<int:cId>', views.inscCurso, name='inscCurso'),
    path('bajaCurso/<int:caID>', views.bajaCurso, name='bajaCurso'),

    #Admin Info Alumnos
    path('InformeDeAlumnos', views.adminInfoAlumnos, name='adminInfoAlumnos'),

    #Preceptor Cursos
    path('preLstCursos', views.preLstCursos, name='preLstCursos'),
    path('preCursoNuevo', views.preCursoNuevo, name='preCursoNuevo'),
    path('preCursoEditar/<int:idCurso>', views.preCursoEditar, name='preCursoEditar'),
    path('preLstAlu', views.preLstAlu, name='preLstAlu'),
    path('preVerAlumno/<int:aluID>', views.preVerAlumno, name='preVerAlumno'),
    path('preNotAsi/<int:cId>', views.preNotAsi, name='preNotAsi'),
]

CentrosDeFormacion/urls.py
from django.contrib import admin
from django.urls import path, include

# Importo el archivo settings para poder trabajar con los
# valores asignados a "MEDIA_URL" y "MEDIA_ROOT"
from django.conf import settings

# Importo los archivos estaticos
# Esto me permite agregar a "urlpatterns"
# la ruta a las imagenes
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CFP.urls')),
    path('', include("Usuarios.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CFP/models.py
from django.db import models
from django.db.models.deletion import DO_NOTHING
from django.db.models.fields import CharField
from django.core.validators import MinValueValidator


# Create your models here.

# region Utiles
class Localidad(models.Model):
    nombre = models.CharField(max_length=50)
    def __str__(self):
        return self.nombre

class diaHora(models.Model):
    dia = models.CharField(max_length=9)
    horaInicio = models.CharField(max_length=6)
    horaFin = models.CharField(max_length=6)
    def __str__(self):
        return self.dia
#endregion utiles


class CentroDeFormacion(models.Model):
    nombre = CharField(max_length=20)
    localidad = models.ForeignKey(Localidad, on_delete=DO_NOTHING)
    calle = models.CharField(max_length=150)
    altura = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    entre = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.nombre


class Curso(models.Model):
    nombre = models.CharField(max_length=200)
    cenForm = models.ForeignKey(CentroDeFormacion, on_delete=DO_NOTHING)
    inscAbierta = models.BooleanField(default=False)
    habilitado = models.BooleanField(default=False)
    practico = models.BooleanField(default=False)
    cantHoras = models.PositiveIntegerField(validators=[MinValueValidator(4)])
    cupoMin = models.PositiveBigIntegerField(validators=[MinValueValidator(1)])
    cupoMax = models.PositiveBigIntegerField(validators=[MinValueValidator(1)])
    fechaInicio = models.DateField()
    fechaFin = models.DateField()
    diasHorarios = models.ManyToManyField(diaHora)
    
    #region Evitar Error De Referencia Circular
    # https://stackoverflow.com/questions/28868610/django-importerror-cannot-import-model#28869260
    # No me deja importar el modelo "Profesor" de la app "Usuarios" porque me devuelve
    # un error relacionado con referencia circular, aunque no hay ninguna referencia
    # circular...
    # La solucion (stackoverflow) es definir el parámetro que corresponde al modelo en la relacion
    # como un string con la forma "App.Modelo" y de ese modo se evita el import que genera
    # el error.
    # endregion 
    profesor = models.ForeignKey('Usuarios.Profesor', null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.nombre

    def get_alumnos(self):
        alumnos = self.cursoalumno_set.all()
        return alumnos

    def get_aprobado(self):
        aprobados = self.cursoalumno_set.filter(aprobado = True)
        return aprobados

Usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.deletion import DO_NOTHING
from CFP.models import CentroDeFormacion, Localidad, Curso
# Create your models here.
"""
Por ahora solo voy a crear Alumno y Profesor
Para el usuario Administrador uso el usuario
que implementa el framework
"""

class appUser(AbstractUser):
    es_alumno = models.BooleanField(default=False)
    es_profesor = models.BooleanField(default=False)
    es_preceptor = models.BooleanField(default=False)

    def __str__(self):
        return self.username



class Alumno(models.Model):
    #nombre = es el campo "first_name" de AbstractUser
    #apellido = es el campo "last_name" de AbstractUser
    usr_alumno = models.OneToOneField(appUser, on_delete=models.CASCADE, primary_key=True)

    Dni = models.PositiveIntegerField(unique=True, validators=[MinValueValidator(20000000), MaxValueValidator(99999999)])
    
    fecha_nacimiento = models.DateField()

    # "upload_to" especifica la subcarpeta dentro de "zMedia" en donde se van a subir las imagenes
    DniImg = models.ImageField(upload_to='alumnos')
    Autorizacion = models.ImageField(blank=True, null=True, upload_to='alumnos/')

    Telefono = models.CharField(max_length=20)
    #email= es el campo "email" de AbstractUser
    #OJO edité "AbstractUser" (/django/contrib/auth/models.py) para que el campo email sea único
    calle = models.CharField(max_length=100)
    altura = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    entre = models.CharField(max_length=200)

    localidad = models.ForeignKey(Localidad, on_delete=DO_NOTHING)

    curso = models.ManyToManyField(Curso, through='CursoAlumno')

    def __str__(self):
        return self.usr_alumno.username



# Este modelo deberia estar en la aplicacion CFP, pero lo pongo acá
# porque sino el framework me devuelve error E331
class CursoAlumno(models.Model):
    alumno = models.ForeignKey(Alumno, on_delete=DO_NOTHING)
    curso = models.ForeignKey(Curso, on_delete=DO_NOTHING)
    #porcAsist = models.PositiveIntegerField(validators=[MaxValueValidator(100)])
    porcAsist = models.FloatField(blank=True, null=True, validators=[MinValueValidator(0), MaxValueValidator(100)])
    notaCurso = models.PositiveIntegerField(blank=True, null=True, validators=[MaxValueValidator(10)])
    aprobado = models.BooleanField(default=False)



class Profesor(models.Model):
    usr_profesor = models.OneToOneField(appUser, on_delete=models.CASCADE, primary_key=True)
    dni = models.PositiveIntegerField(unique=True, validators=[MinValueValidator(20000000), MaxValueValidator(99999999)])
    telefono = models.CharField(max_length=20)
    #nombre = es el campo "first_name" de AbstractUser
    #apellido = es el campo "last_name" de AbstractUser
    #email= es el campo "email" de AbstractUser
    #OJO edité "AbstractUser" (/django/contrib/auth/models.py) para que el campo email sea único

    def __str__(self):
        name = self.usr_profesor.first_name
        lname = self.usr_profesor.last_name
        fname = str(name+' '+lname)
        return fname



class Preceptor(models.Model):
    usr = models.OneToOneField(appUser, on_delete=models.CASCADE, primary_key=True)
    telefono = models.CharField(max_length=20)
    cfp = models.ForeignKey(CentroDeFormacion, on_delete=models.CASCADE)

CFP/forms.py
from django import forms
from django.forms import ModelForm

from .models import Curso, Localidad, CentroDeFormacion

class frmLocalidad(ModelForm):
    class Meta:
        model = Localidad
        fields = '__all__'



class frmCentroFormacion(ModelForm):
    class Meta:
        model = CentroDeFormacion
        fields = '__all__'



class widgetFecha(forms.DateInput):
    input_type = 'date'


class frmCursos(ModelForm):
    class Meta:
        model = Curso

        fields = [
            'nombre',
            'cenForm',
            'profesor',
            'inscAbierta',
            'habilitado',
            'practico',
            'cupoMin',
            'cupoMax',
            'cantHoras',
            'fechaInicio',
            'fechaFin',
        ]

        labels = {
            'nombre':'Nombre',
            'cenForm':'Centro De Formacion',
            'inscAbierta': 'Inscripcion Abierta',
            'practico':'Curso Practico',
            'cupoMin':'Cupo Minimo',
            'cupoMax':'Cupo Maximo',
            'cantHoras':'Cantidad De Horas',
            'fechaInicio':'Fecha De Inicio',
            'fechaFin':'Fecha De Finalizacion'
        }

        widgets = {
            'fechaInicio' : widgetFecha(),
            'fechaFin' : widgetFecha()
        }



#region Preceptor
class preFrmCursos(ModelForm):
    class Meta:
        model = Curso

        fields = [
            'nombre',
            'profesor',
            'inscAbierta',
            'habilitado',
            'practico',
            'cupoMin',
            'cupoMax',
            'cantHoras',
            'fechaInicio',
            'fechaFin',
        ]

        labels = {
            'nombre':'Nombre',
            'inscAbierta': 'Inscripcion Abierta',
            'practico':'Curso Practico',
            'cupoMin':'Cupo Minimo',
            'cupoMax':'Cupo Maximo',
            'cantHoras':'Cantidad De Horas',
            'fechaInicio':'Fecha De Inicio',
            'fechaFin':'Fecha De Finalizacion'
        }

        widgets = {
            'fechaInicio' : widgetFecha(),
            'fechaFin' : widgetFecha()
        }
#endregion

CFP/templates/CFP/cursosForm.html
{% extends 'Usuarios/menuAdmin.html' %}


{% block Contenido %}

    {% load crispy_forms_tags %}
    
    <form action="" method="post" id="frmCrear" autocomplete="off" class="m-4">
        {% csrf_token %}
        {{form | crispy}}

        <p>
            <input type="checkbox" class="dias" id="lunes" name="dias" value="Lunes">
            <label for="dias">Lunes</label>
            <input type="time" class="LunesI" name="horaInicio" id="" disabled>
            <input type="time" class="LunesF" name="horaFin" id="" disabled>
            <span class="ml-2" id="Lunes" style="color: red;"></span>
        </p>

        <p>
            <input type="checkbox" class="dias" id="" name="dias" value="Martes">
            <label for="dias">Martes</label>
            <input type="time" class="MartesI" name="horaInicio" id="" disabled>
            <input type="time" class="MartesF" name="horaFin" id="" disabled>
            <span class="ml-2" id="Martes" style="color: red;"></span>
            
        </p>

        <p>
            <input type="checkbox" class="dias" id="" name="dias" value="Miercoles">
            <label for="dias">Miercoles</label>
            <input type="time" class="MiercolesI" name="horaInicio" id="" disabled>
            <input type="time" class="MiercolesF" name="horaFin" id="" disabled>
            <span class="ml-2" id="Miercoles" style="color: red;"></span>
            
        </p>

        <p>
            <input type="checkbox" class="dias" id="" name="dias" value="Jueves">
            <label for="dias">Jueves</label>
            <input type="time" class="JuevesI" name="horaInicio" id="" disabled>
            <input type="time" class="JuevesF" name="horaFin" id="" disabled>
            <span class="ml-2" id="Jueves" style="color: red;"></span>
            
        </p>

        <p>
            <input type="checkbox" class="dias" id="" name="dias" value="Viernes">
            <label for="dias">Viernes</label>
            <input type="time" class="ViernesI" name="horaInicio" id="" disabled>
            <input type="time" class="ViernesF" name="horaFin" id="" disabled>
            <span class="ml-2" id="Viernes" style="color: red;"></span>
            
        </p>

        <p>
            <input type="checkbox" class="dias" id="" name="dias" value="Sabado">
            <label for="dias">Sabado</label>
            <input type="time" class="SabadoI" name="horaInicio" id="" disabled min="07:00" max="22:00">
            <input type="time" class="SabadoF" name="horaFin" id="" disabled min="07:00" max="22:00">
            <span class="ml-2" id="Sabado" style="color: red;"></span>
            
        </p>

        <input type="submit" id="btnGuardar" class="btn btn-success" value="Guardar">
        <a href="{% url 'cursos' %}" class="btn btn-danger">Cancelar</a>
    </form>

    
{% endblock Contenido %}


{% block jquery %}
<script>
    let Dias = $('input[name="dias"]')

    //Funcionalidad para habilitar la edicion de los inputs tipo time
    //Cuando cambia el estado de un checkbox
    $('.dias').change(function(){
        //pruebas
        //alert('clicked')

        //Creo una array con todos los inputs (checkbox) con nombre "dias"
        let checks = $('input[name="dias"]')
        //pruebas
        //console.log(checks.length);

        //Por cada elemento del array, cada checkbox
        $(checks).each(function(){
            //pruebas
            //console.log(this.value)
            //pruebas
            //$('.habilitar').prop("disabled", false);
            
            //Guardo el valor del checkbox, que tambien es el nombre de la clase de los
            //inputs de tipo "time" que le corresponde a cada checkbox
            let claseTime = this.value
            
            //Si el checkbox es "tildado"
            if ($(this).is(":checked")){
                //pruebas
                //alert("Clase: "+clase)

                //Le saco la propiedad "disaabled" a los "time" con esa clase
                $('.'+claseTime+'I').prop("disabled", false);
                $('.'+claseTime+'F').prop("disabled", false);

            }
            //Si el checkbox no es "tildado"
            else{
                //pruebas
                //alert('naditas')

                //Le agrego la propiedad "disabled" a los time con esa clase
                $('.'+claseTime+'I').prop("disabled", true);
                $('.'+claseTime+'F').prop("disabled", true);
                
                //Borro el valor que tiene el input "time"
                $('.'+claseTime+'I').val("");
                $('.'+claseTime+'F').val("");
                
            }

        })
    })


    //Validar que input time no este vacio si checkbox es checked
    //Cada vez que se encuentre un input vacio al recorrer el array "Dias"
    //se agrega un elemento al array "vacios"
    let errores = []

    $('#btnGuardar').click(function(e){
        e.preventDefault()
        
        /*Limpio el array de para que cada vez que se itera solo esten los
        valores que realmente esten vacios*/
        errores = []
        console.clear();

        //Itero sobre cada elemento de "Dias"
        $(Dias).each(function(){

            //Guardo la clase del checkbox
            let clase = this.value

            //Limpio el span que muestra mensaje de error de cada input
            $('#'+clase).text('')

            //Si el checkbox es "tildado"
            if ($(this).is(":checked")){
                
                //Guardo el string que representa el nombre de la clase para
                //los inputs tipo time
                let itimeI = $('.'+clase+'I')
                let itimeF = $('.'+clase+'F')
                
                //si el input time está vacio
                if( (itimeI.val() == "") || (itimeF.val() == "") ){
                    
                    //Agrego un elemento a la lista vacios
                    errores.push($(this))
                    console.clear()
                    console.log('Vacios: '+errores.length+' Input: '+clase)
                    
                    //Le asigno al span un mensaje de error
                    $('#'+clase).append('Completar Valores')
                
                // RANGO DE HORARIOS
                //Inicio
                }else if (itimeI.val()<"07:00" | itimeI.val()>"22:00"){
                    errores.push($(this))
                    console.clear()
                    console.log('iTimeI: '+errores.length)
                    $('#'+clase).append('El horario debe ser entre 7am y 10pm ')

                }else if (itimeF.val()<"07:00" | itimeF.val()>"22:00"){
                    errores.push($(this))
                    console.clear()
                    console.log('iTimeF: '+errores.length)
                    $('#'+clase).append('El horario debe ser entre 7am y 10pm ')

                }else if (itimeI.val()>itimeF.val()){
                    errores.push($(this))
                    console.clear()
                    console.log('ALVESRRRE: '+errores.length)
                    $('#'+clase).append('El Horario De Inicio Debe Ser Menor Al De Fin ')
                }   
            }
            
        })
        
        //Fecha Actual
        let fechaActual = new Date();
            
            //Tomo el valor de Fecha De Inicio
        let valFechaInic = $('#id_fechaInicio').val();
        
        //Concateno a "valFechaInic" hh:mm:ss para poder convertir a Date()
        let valFechaCompleto = valFechaInic+"T00:00:00";

        //Convierto "valFechaCompleto" a tipo Date()
        let fechaInputDate = new Date(valFechaCompleto);

        let fIni = $('#id_fechaInicio').val()
        let fFin = $('#id_fechaFin').val()
                        
        if (fechaInputDate < fechaActual){
            errores.push(fechaInputDate);
            alert('La Fecha De Inicio Del Curso No Puede Ser Anterior A Hoy');
            console.log(errores);

        }else if (fIni > fFin){
            errores.push(fIni, fFin);
            alert('La Fecha De Inicio Del Curso Debe Ser Anterior A la Fecha De Finalizacion');
            console.log(errores);
        }
        
        if (errores.length == 0){
            console.log( "Envia Calores por POST | Errores: "+ errores.length);
            //Envio el formulario
            $('#frmCrear').submit()
        }

    })
</script>
{% endblock jquery %}
    

CFP/templates/CFP/cursosFormEdit.html
{% extends 'Usuarios/menuAdmin.html' %}


{% block Contenido %}

    {% load crispy_forms_tags %}
    
    <form action="" method="post" id="frmEdit" autocomplete="off" class="m-4">
        {% csrf_token %}
        <di class="form-row">
            <div class="col-md-6">
                {{form.nombre | as_crispy_field}}
            </div>
            <div class="col-md-6">
                {{form.cenForm | as_crispy_field}}
            </div>
        </di>
        <div class="form-row mt-4 mb-4">
            <div class="col-md-4">
                {{form.inscAbierta | as_crispy_field}}
            </div>
            <div class="col-md-4">
                {{form.habilitado | as_crispy_field}}
            </div>
            <div class="col-md-4">
                {{form.practico | as_crispy_field}}
            </div>
        </div>
        <div class="form-row mb-4">
            <div class="col-md-2">
                {{form.cantHoras | as_crispy_field}}
            </div>
            <div class="col-md-3">
                {{form.fechaInicio | as_crispy_field}}
            </div>
            <div class="col-md-3 mb-5">
                {{form.fechaFin | as_crispy_field}}
            </div>
            <div class="col-md-4 mb-5">
                {{form.profesor | as_crispy_field}}
            </div>
        </div>

        <div class="form-row mb-4">
            
            <div class="col-md-4">
                {{form.cupoMin | as_crispy_field}}
            </div>
            <div class="col-md-4 mb-5">
                {{form.cupoMax | as_crispy_field}}
            </div>
        </div>

        
        <hr class="mt-4">

        <p class="h5 text-center">Dias y Horarios En los que se dicta el curso</p>
        
        <div class="form-row">
            {% for dia in curso.diasHorarios.all %}
                
            <div class="col-md-3">
                <p>{{dia}} De: {{dia.horaInicio}} a {{dia.horaFin}}</p>
            </div>    
            
            
            {% endfor %}
        </div>

        <hr>
        <p class="h5 text-center">Editar Dias y Horarios</p>
        
        <p>
            <input type="checkbox" class="dias" id="lunes" name="dias" value="Lunes">
            <label for="dias">Lunes</label>
            <input type="time" class="LunesI" name="horaInicio" id="" disabled>
            <input type="time" class="LunesF" name="horaFin" id="" disabled>
            <span class="ml-2" id="Lunes" style="color: red;"></span>
        </p>

        <p>
            <input type="checkbox" class="dias" id="" name="dias" value="Martes">
            <label for="dias">Martes</label>
            <input type="time" class="MartesI" name="horaInicio" id="" disabled>
            <input type="time" class="MartesF" name="horaFin" id="" disabled>
            <span class="ml-2" id="Martes" style="color: red;"></span>
            
        </p>

        <p>
            <input type="checkbox" class="dias" id="" name="dias" value="Miercoles">
            <label for="dias">Miercoles</label>
            <input type="time" class="MiercolesI" name="horaInicio" id="" disabled>
            <input type="time" class="MiercolesF" name="horaFin" id="" disabled>
            <span class="ml-2" id="Miercoles" style="color: red;"></span>
            
        </p>

        <p>
            <input type="checkbox" class="dias" id="" name="dias" value="Jueves">
            <label for="dias">Jueves</label>
            <input type="time" class="JuevesI" name="horaInicio" id="" disabled>
            <input type="time" class="JuevesF" name="horaFin" id="" disabled>
            <span class="ml-2" id="Jueves" style="color: red;"></span>
            
        </p>

        <p>
            <input type="checkbox" class="dias" id="" name="dias" value="Viernes">
            <label for="dias">Viernes</label>
            <input type="time" class="ViernesI" name="horaInicio" id="" disabled>
            <input type="time" class="ViernesF" name="horaFin" id="" disabled>
            <span class="ml-2" id="Viernes" style="color: red;"></span>
            
        </p>

        <p>
            <input type="checkbox" class="dias" id="" name="dias" value="Sabado">
            <label for="dias">Sabado</label>
            <input type="time" class="SabadoI" name="horaInicio" id="" disabled min="07:00" max="22:00">
            <input type="time" class="SabadoF" name="horaFin" id="" disabled min="07:00" max="22:00">
            <span class="ml-2" id="Sabado" style="color: red;"></span>
            
        </p>

        <input type="submit" id="btnGuardar" class="btn btn-success" value="Guardar">
        <a href="{% url 'cursos' %}" class="btn btn-danger">Cancelar</a>
    </form>

    
{% endblock Contenido %}


{% block jquery %}
<script>
    let Dias = $('input[name="dias"]')

    //Funcionalidad para habilitar la edicion de los inputs tipo time
    //Cuando cambia el estado de un checkbox
    $('.dias').change(function(){
        //pruebas
        //alert('clicked')

        //Creo una array con todos los inputs (checkbox) con nombre "dias"
        let checks = $('input[name="dias"]')
        //pruebas
        //console.log(checks.length);

        //Por cada elemento del array, cada checkbox
        $(checks).each(function(){
            //pruebas
            //console.log(this.value)
            //pruebas
            //$('.habilitar').prop("disabled", false);
            
            //Guardo el valor del checkbox, que tambien es el nombre de la clase de los
            //inputs de tipo "time" que le corresponde a cada checkbox
            let claseTime = this.value
            
            //Si el checkbox es "tildado"
            if ($(this).is(":checked")){
                //pruebas
                //alert("Clase: "+clase)

                //Le saco la propiedad "disaabled" a los "time" con esa clase
                $('.'+claseTime+'I').prop("disabled", false);
                $('.'+claseTime+'F').prop("disabled", false);

            }
            //Si el checkbox no es "tildado"
            else{
                //pruebas
                //alert('naditas')

                //Le agrego la propiedad "disabled" a los time con esa clase
                $('.'+claseTime+'I').prop("disabled", true);
                $('.'+claseTime+'F').prop("disabled", true);
                
                //Borro el valor que tiene el input "time"
                $('.'+claseTime+'I').val("");
                $('.'+claseTime+'F').val("");
                
            }

        })
    })


    //Validar que input time no este vacio si checkbox es checked
    //Cada vez que se encuentre un input vacio al recorrer el array "Dias"
    //se agrega un elemento al array "vacios"
    let errores = []

    $('#btnGuardar').click(function(e){
        e.preventDefault()
        
        /*Limpio el array de para que cada vez que se itera solo esten los
        valores que realmente esten vacios*/
        errores = []
        console.clear();

        //Itero sobre cada elemento de "Dias"
        $(Dias).each(function(){

            //Guardo la clase del checkbox
            let clase = this.value

            //Limpio el span que muestra mensaje de error de cada input
            $('#'+clase).text('')

            //Si el checkbox es "tildado"
            if ($(this).is(":checked")){
                
                //Guardo el string que representa el nombre de la clase para
                //los inputs tipo time
                let itimeI = $('.'+clase+'I')
                let itimeF = $('.'+clase+'F')
                
                //si el input time está vacio
                if( (itimeI.val() == "") || (itimeF.val() == "") ){
                    
                    //Agrego un elemento a la lista vacios
                    errores.push($(this))
                    console.clear()
                    console.log('Vacios: '+errores.length+' Input: '+clase)
                    
                    //Le asigno al span un mensaje de error
                    $('#'+clase).append('Completar Valores')
                
                // RANGO DE HORARIOS
                //Inicio
                }else if (itimeI.val()<"07:00" | itimeI.val()>"22:00"){
                    errores.push($(this))
                    console.clear()
                    console.log('iTimeI: '+errores.length)
                    $('#'+clase).append('El horario debe ser entre 7am y 10pm ')

                }else if (itimeF.val()<"07:00" | itimeF.val()>"22:00"){
                    errores.push($(this))
                    console.clear()
                    console.log('iTimeF: '+errores.length)
                    $('#'+clase).append('El horario debe ser entre 7am y 10pm ')

                }else if (itimeI.val()>itimeF.val()){
                    errores.push($(this))
                    console.clear()
                    console.log('ALVESRRRE: '+errores.length)
                    $('#'+clase).append('El Horario De Inicio Debe Ser Menor Al De Fin ')
                }   
            }
            
        })
        
        //Fecha Actual
        let fechaActual = new Date();
            
            //Tomo el valor de Fecha De Inicio
        let valFechaInic = $('#id_fechaInicio').val();
        
        //Concateno a "valFechaInic" hh:mm:ss para poder convertir a Date()
        let valFechaCompleto = valFechaInic+"T00:00:00";

        //Convierto "valFechaCompleto" a tipo Date()
        let fechaInputDate = new Date(valFechaCompleto);

        let fIni = $('#id_fechaInicio').val()
        let fFin = $('#id_fechaFin').val()
                        
        if (fechaInputDate < fechaActual){
            errores.push(fechaInputDate);
            alert('La Fecha De Inicio Del Curso No Puede Ser Anterior A Hoy');
            console.log(errores);

        }else if (fIni > fFin){
            errores.push(fIni, fFin);
            alert('La Fecha De Inicio Del Curso Debe Ser Anterior A la Fecha De Finalizacion');
            console.log(errores);
        }
        
        if (errores.length == 0){
            console.log( "Envia Calores por POST | Errores: "+ errores.length);
            //Envio el formulario
            $('#frmEdit').submit()
        }

    })
</script>
{% endblock jquery %}

CFP/templates/CFP/localidadForm.html
{% extends 'Usuarios/menuAdmin.html' %}


{% block Contenido %}

    {% load crispy_forms_tags %}
    
    <form action="" method="post" autocomplete="off">
        {% csrf_token %}
        {{form | crispy}}

        <input type="submit" class="btn btn-success" value="Guardar">
        <a href="{% url 'localidades' %}" class="btn btn-danger">Cancelar</a>
    </form>
    
{% endblock Contenido %}
    