CFP/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('misCursos', views.misCursos, name='misCursos'),

    #Localidades
    path('localidadNueva', views.localidadNueva, name='localidadNueva'),
    path('localidades', views.localidades, name='localidades'),
    path('localidadEditar/<int:idLocalidad>', views.localidadEditar, name='localidadEditar'),
    path('localidadBorrar/<int:idLocalidad>', views.localidadBorrar, name='localidadBorrar'),

    #Centros De Formacion
    path('centroNuevo', views.centroNuevo, name='centroNuevo'),
    path('centros', views.centros, name='centros'),
    path('centrosEditar/<int:idCentro>', views.centroEditar, name='centrosEditar'),

    #Cursos
    path('cursoNuevo', views.cursoNuevo, name='cursoNuevo'),
    path('cursos', views.cursoLista, name='cursos'),
    path('cursosInfo', views.cursoInfo, name='cursosInfo'),
    path('cursoEditar/<int:idCurso>', views.cursoEditar, name='cursoEditar'),
    path('inscCurso/<int:cId>', views.inscCurso, name='inscCurso'),
    path('bajaCurso/<int:caID>', views.bajaCurso, name='bajaCurso'),

    #Admin Info Alumnos
    path('InformeDeAlumnos', views.adminInfoAlumnos, name='adminInfoAlumnos'),

    #Preceptor Cursos
    path('preLstCursos', views.preLstCursos, name='preLstCursos'),
    path('preCursoNuevo', views.preCursoNuevo, name='preCursoNuevo'),
    path('preCursoEditar/<int:idCurso>', views.preCursoEditar, name='preCursoEditar'),
    path('preLstAlu', views.preLstAlu, name='preLstAlu'),
    path('preVerAlumno/<int:aluID>', views.preVerAlumno, name='preVerAlumno'),
    path('preNotAsi/<int:cId>', views.preNotAsi, name='preNotAsi'),
]

CentrosDeFormacion/urls.py
from django.contrib import admin
from django.urls import path, include

# Importo el archivo settings para poder trabajar con los
# valores asignados a "MEDIA_URL" y "MEDIA_ROOT"
from django.conf import settings

# Importo los archivos estaticos
# Esto me permite agregar a "urlpatterns"
# la ruta a las imagenes
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CFP.urls')),
    path('', include("Usuarios.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Usuarios/urls.py
from collections import namedtuple
from django.urls import path
from Usuarios import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.logIn, name='login'),
    path('menu', views.menu, name='menu'),

    #Profesores
    path('profesores', views.lstProfesores, name='profesores'),
    path('crearProfesor', views.crearProfesor, name='crearProfesor'),
    path('editProf/<int:idUsr>', views.editarProfesor, name='editProf'),
    path('deshabProf/<int:idUsr>', views.profDeshabilitar, name='deshabProf'),

    #Preceptores
    path('preceptores', views.lstPreceptores, name='preceptores'),
    path('crearPreceptor', views.crearPreceptor, name='crearPreceptor'),
    path('editPrec/<idUsr>', views.editarPreceptor, name='editPrec'),
    path('deshabPrec/<idUsr>', views.deshabilitarPreceptor, name='deshabPrec'),

    #Alumno
    path('crearAlumno', views.crearAlumno, name='crearAlumno'),
    path('borrarAlumno/<int:aID>', views.borrarAlumno, name='borrarAlumno')
]

# Ruta para las imagenes
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.deletion import DO_NOTHING
from CFP.models import CentroDeFormacion, Localidad, Curso
# Create your models here.
"""
Por ahora solo voy a crear Alumno y Profesor
Para el usuario Administrador uso el usuario
que implementa el framework
"""

class appUser(AbstractUser):
    es_alumno = models.BooleanField(default=False)
    es_profesor = models.BooleanField(default=False)
    es_preceptor = models.BooleanField(default=False)

    def __str__(self):
        return self.username



class Alumno(models.Model):
    #nombre = es el campo "first_name" de AbstractUser
    #apellido = es el campo "last_name" de AbstractUser
    usr_alumno = models.OneToOneField(appUser, on_delete=models.CASCADE, primary_key=True)

    Dni = models.PositiveIntegerField(unique=True, validators=[MinValueValidator(20000000), MaxValueValidator(99999999)])
    
    fecha_nacimiento = models.DateField()

    # "upload_to" especifica la subcarpeta dentro de "zMedia" en donde se van a subir las imagenes
    DniImg = models.ImageField(upload_to='alumnos')
    Autorizacion = models.ImageField(blank=True, null=True, upload_to='alumnos/')

    Telefono = models.CharField(max_length=20)
    #email= es el campo "email" de AbstractUser
    #OJO edité "AbstractUser" (/django/contrib/auth/models.py) para que el campo email sea único
    calle = models.CharField(max_length=100)
    altura = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    entre = models.CharField(max_length=200)

    localidad = models.ForeignKey(Localidad, on_delete=DO_NOTHING)

    curso = models.ManyToManyField(Curso, through='CursoAlumno')

    def __str__(self):
        return self.usr_alumno.username



# Este modelo deberia estar en la aplicacion CFP, pero lo pongo acá
# porque sino el framework me devuelve error E331
class CursoAlumno(models.Model):
    alumno = models.ForeignKey(Alumno, on_delete=DO_NOTHING)
    curso = models.ForeignKey(Curso, on_delete=DO_NOTHING)
    #porcAsist = models.PositiveIntegerField(validators=[MaxValueValidator(100)])
    porcAsist = models.FloatField(blank=True, null=True, validators=[MinValueValidator(0), MaxValueValidator(100)])
    notaCurso = models.PositiveIntegerField(blank=True, null=True, validators=[MaxValueValidator(10)])
    aprobado = models.BooleanField(default=False)



class Profesor(models.Model):
    usr_profesor = models.OneToOneField(appUser, on_delete=models.CASCADE, primary_key=True)
    dni = models.PositiveIntegerField(unique=True, validators=[MinValueValidator(20000000), MaxValueValidator(99999999)])
    telefono = models.CharField(max_length=20)
    #nombre = es el campo "first_name" de AbstractUser
    #apellido = es el campo "last_name" de AbstractUser
    #email= es el campo "email" de AbstractUser
    #OJO edité "AbstractUser" (/django/contrib/auth/models.py) para que el campo email sea único

    def __str__(self):
        name = self.usr_profesor.first_name
        lname = self.usr_profesor.last_name
        fname = str(name+' '+lname)
        return fname



class Preceptor(models.Model):
    usr = models.OneToOneField(appUser, on_delete=models.CASCADE, primary_key=True)
    telefono = models.CharField(max_length=20)
    cfp = models.ForeignKey(CentroDeFormacion, on_delete=models.CASCADE)

Usuarios/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect

from Usuarios.forms import frmAlumno, frmPreceptor, frmUsuario, frmProfesor, frmUsrProf, Preceptor
from .models import Alumno, Profesor, appUser
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from CFP.models import CentroDeFormacion, Curso, Localidad

# Create your views here.

@login_required
def logIn(request):
    if request.user.is_authenticated:
        return redirect('/menu')
    else:
        return redirect('accounts/login')


@login_required
def menu(request):
    
    if request.user.is_superuser:
        adminCtxt={
            'titulo':'Menu De Administracion'
        }
        return render(request, 'Usuarios/menuAdmin.html', adminCtxt)
    
    elif request.user.es_preceptor:
        user = appUser.objects.get(pk=request.user.id)
        precCtxt={
            'usuario':user,
            'titulo':'Preceptor'
        }
        
        return render(request, 'Usuarios/menuPreceptor.html', precCtxt)
        
    else:
        return redirect('/')



#region CRUD Alumno
def crearAlumno(request):
    ctxtGET = {
        'formAlumno': frmAlumno(),
        'formUser': frmUsuario,
        'titulo': 'Registrarse Como Alumno'
    }


    if request.method == 'POST':

        usrPost = frmUsuario(request.POST)

        #region "request.FILES"
        # OJO, para levantar los valores de los campos con archivos
        # Tengo que usar request.FILES ya que request.POST solo me
        # trae los valores de los inputs que no contienen archivos
        #endregion
        aluPost = frmAlumno(request.POST, request.FILES)

        if usrPost.is_valid() and aluPost.is_valid():
            #region Obtengo los valores de los formularios
            #appUser
            nombre = request.POST.get('first_name')
            apellido = request.POST.get('last_name')
            mail = request.POST.get('email')
            pswd = request.POST.get('password')

            #Alumno
            dni = request.POST.get('Dni')
            fNac = request.POST.get('fecha_nacimiento')
            
            # Acá uso "request.FILES" para obtener el
            # valor del input que contiene un archivo
            dni_img = request.FILES.get('DniImg')
            
            #region Cambio Nombre De La Imagen
            # Como nombre le pongo el dni
            nameImg = dni_img.name
            splittedN, splittedE = nameImg.split('.')
            splittedN = dni
            dni_img.name = splittedN+"."+splittedE
            #endregion

            autoriza = request.FILES.get('Autorizacion')
            tel = request.POST.get('Telefono')
            calle = request.POST.get('calle')
            altura = request.POST.get('altura')
            entre = request.POST.get('entre')


            loc = request.POST.get('localidad')
            #endregion
            #print(type(dni_img))
            #Instancio "appUser"
            usuario = appUser(
                first_name = nombre,
                last_name = apellido,
                email = mail,
                password = pswd
            )

            usuario.set_password(pswd)
            usuario.username = mail
            usuario.es_alumno = True
            usuario.save()
            

            #Instancio Alumno
            alumno = Alumno(
                usr_alumno = usuario,
                Dni = dni,
                fecha_nacimiento = fNac,
                DniImg = dni_img,
                Autorizacion = autoriza,
                Telefono = tel,
                calle = calle,
                altura = altura,
                entre = entre,
                localidad = Localidad.objects.get(pk=loc)
            )
            alumno.save()
            
            return redirect('login')

        else:
            for mensaje in usrPost.errors:
                messages.error(request, usrPost.errors[mensaje])
                return render(request, 'Usuarios/formAlumno.html',
                {
                    'formAlumno': aluPost,
                    'formUser': usrPost,
                    'titulo':'Registrarse Como Alumno'
                })

            for mensaje in aluPost.errors:
                messages.error(request, aluPost.errors[mensaje])
                return render(request, 'Usuarios/formAlumno.html',
                {
                    'formAlumno': aluPost,
                    'formUser': usrPost,
                    'titulo':'Registrarse Como Alumno'
                })

    else:
        return render(request, 'Usuarios/formAlumno.html', ctxtGET)



@login_required
def borrarAlumno(request, aID):
    if request.user.is_superuser:
        alumno = Alumno.objects.get(pk=aID)
        usr = appUser.objects.get(pk=aID)

        alumno.delete()
        usr.delete()

        return redirect('adminInfoAlumnos')
#endregion



#region CRUD Profesores
@login_required
def lstProfesores(request):
    if request.user.is_superuser:
        profesores = appUser.objects.all().filter(es_profesor=True)
        ctx={
            'profesores': profesores,
            'titulo': 'Profesores'
        }
        return render(request, 'Usuarios/profesores.html', ctx)
    else:
        return redirect('login')



@login_required
def crearProfesor(request):
    if request.user.is_superuser:
        getDict={
            'titulo': 'Registrar Nuevo Profesor',
            'frmUsuario': frmUsrProf(),
            'formProfesor': frmProfesor()
        }
        if request.method == 'POST':
            frmPostU = frmUsrProf(request.POST)
            frmPostP = frmProfesor(request.POST)
            if frmPostP.is_valid() and frmPostU.is_valid():
                nombre = request.POST.get('first_name')
                apellido = request.POST.get('last_name')
                mail = request.POST.get('email')
                pswd = str(nombre).lower()+str(apellido).lower()
                tel = request.POST.get('telefono')
                dni = request.POST.get('dni')

                usuario = appUser(
                    first_name = nombre,
                    last_name = apellido,
                    email = mail,
                    password = pswd
                )
                usuario.set_password(pswd)
                usuario.username = mail
                usuario.es_profesor = True
                usuario.save()

                profe = Profesor(
                    usr_profesor = usuario,
                    telefono = tel,
                    dni = dni

                )
                profe.save()

                """ return HttpResponse(
                    'nombre: {0}</br>Apellido: {1}</br>Email: {2}</br>Password: {3}</br>Telefono: {4}'
                    .format(nombre, apellido, mail, pswd, tel)
                    ) """
                return redirect('profesores')

            else:
                for mensaje in frmPostU.errors:
                    messages.error(request, frmPostU.errors[mensaje])
                    return render(request, 'Usuarios/formProfesor.html',
                    {
                        'formProfesor': frmPostP,
                        'frmUsuario': frmPostU,
                        'titulo':'Registrar Nuevo Profesor'
                    })

                for mensaje in frmPostP.errors:
                    messages.error(request, frmPostP.errors[mensaje])
                    return render(request, 'Usuarios/formProfesor.html',
                    {
                        'formProfesor': frmPostP,
                        'frmUsuario': frmPostU,
                        'titulo':'Registrar Nuevo Profesor'
                    })
        
        else:
            return render(request, 'Usuarios/formProfesor.html', getDict)
        
    else:
        return redirect('home')



@login_required
def editarProfesor(request, idUsr):
    if request.user.is_superuser:
        usr = appUser.objects.get(pk=idUsr)
        profe = Profesor.objects.get(pk=idUsr)

        if request.method == 'GET':
            frmUsr = frmUsrProf(instance=usr)
            frmPro = frmProfesor(instance=profe)

            ctxGet = {
                'titulo': 'Editar Datos De Profesor',
                'frmUsuario': frmUsr,
                'formProfesor': frmPro
            }

            return render(request, 'Usuarios/formProfesor.html', ctxGet)
        
        elif request.method == 'POST':
            usrPost = frmUsrProf(request.POST, instance=usr)
            proPost = frmProfesor(request.POST, instance=profe)

            if usrPost.is_valid() and proPost.is_valid():
                usrPost.save()
                proPost.save()
                return redirect('profesores')
            else:
                for mensaje in usrPost.errors:
                    messages.error(request, usrPost.errors[mensaje])
                    return render(request, 'Usuarios/formProfesor.html',
                    {
                        'formProfesor': proPost,
                        'frmUsuario': usrPost,
                        'titulo':'Editar Datos De Profesor'
                    })

                for mensaje in proPost.errors:
                    messages.error(request, proPost.errors[mensaje])
                    return render(request, 'Usuarios/formProfesor.html',
                    {
                        'formProfesor': proPost,
                        'frmUsuario': usrPost,
                        'titulo':'Editar Datos De Profesor'
                    })
        
        else:
            return HttpResponse('naditas')    
    else:
        return HttpResponse('banana')



@login_required
def profDeshabilitar(request, idUsr):
    usr = appUser.objects.get(pk = idUsr)
    if request.user.is_superuser and usr.es_profesor:
        usr.is_active = False
        usr.save()
        return redirect('profesores')
    else:
        return HttpResponse('naditas')
#endregion



#region CRUD Preceptores
@login_required

Usuarios/templates/Usuarios/formAlumno.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CFPBA: {{titulo}}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'CFP/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'CFP/css/estilos.css' %}">
</head>
<body>
    {% load crispy_forms_tags %}
    
    <div class="container">
        <h2 class="mt-4 text-center mb-4">{{titulo}}</h2>

        <form id="crearAlumno" method="POST" enctype="multipart/form-data" autocomplete="off">
            {% csrf_token %}
            {{formUser | crispy}}
            {{formAlumno | crispy}}
            <button type="submit" id="btnSumbit" class="btn btn-primary">Aceptar</button>
            <button type="reset" class="btn btn-danger">Cancelar</button>
        </form>
    </div>


    <!--JS jQuery, Popper, Bootstrap-->
    <script src=" {% static 'CFP/js/jquery-3.6.0.min.js' %} "></script>
    <script src=" {% static 'CFP/js/popper.min.js' %} "></script>
    <script src=" {% static 'CFP/js/bootstrap.min.js' %} "></script>

    <script>
        /*
        De milisegundo a dia
        1000 ms = 1 s
        60 s = 1 m
        60 m = 1 h
        24 h = 1 d
        (1000*60*60*24) = 1d
        */

        //Funcion para validar la fecha de nacimiento
        // Minimo 16 eños
        // Si menor de 18 pedir autorización
        function validarFecha(){
            //Tomo el valor del campo fecha_nacimiento
            var valFecha = $('#id_fecha_nacimiento').val();
            
            //Concateno a "valFecha" hh:mm:ss para poder convertir a Date()
            var valFechaCompleto = valFecha+"T00:00:00";

            //Convierto "valFechaCompleto" a tipo Date()
            var fechaInputDate = new Date(valFechaCompleto);
            
            //Fecha Actual
            var fechaActual = new Date();
            
            var diferenciaMs = fechaActual.getTime()-fechaInputDate.getTime()
            
            var calcDia = 1000*60*60*24

            //Esta es la diferencia en dias entre la fecha actual y la 
            //ingresada en el input
            var diferenciaDIAS = Math.round(diferenciaMs/calcDia)

            //console.log("Diferencia En Dias: "+diferenciaDIAS);

            autorizacion = $('#id_Autorizacion').val()

            // Si la fecha ingresada es mayor a la fecha actual
            if (fechaInputDate>fechaActual){
                alert("La 'Fecha De Nacimiento' no puede ser superior a la fecha actual")
                $('#id_fecha_nacimiento').addClass('bg-warning')
            
            // Si la fecha ingresada es menor a 16 años respecto de la fecha actual
            }else if (diferenciaDIAS < 5840){
                alert('No se permite inscripcion a menores de 16 años')
                $('#id_fecha_nacimiento').addClass('bg-warning')
            
            // Si la fecha ingresada es menor a 18 años respecto de
            // la fecha actual, mayor a 16 y no adjunta autorizacion
            }else if (diferenciaDIAS<6570 && diferenciaDIAS>=5840 && autorizacion==='' ){
                
                alert('Si sos menor de 18 años por favor adjunta una autorizacion de tus padres para inscribirte')
                $('#id_Autorizacion').addClass('bg-warning')
                $('#id_Autorizacion').focus()
            }else{
                //Si no ocurre ninguna de las condiciones anteriores
                //se envía el formulario
                $('#crearAlumno').submit()
            }

        };

        $('#btnSumbit').click(function(){
            //Evito que el boton del form haga el envío
            event.preventDefault();

            //Llamo a la función para validar la fecha de nacimiento
            validarFecha();
        })

    </script>
</body>
</html>

Usuarios/templates/Usuarios/formPreceptor.html
{% extends 'Usuarios/menuAdmin.html' %}

{% block Contenido %}

    {% load crispy_forms_tags %}
    
    <div class="container">

        <form method="POST" autocomplete="off">
            {% csrf_token %}
            
            {{frmUsuario | crispy}}
            {{formPreceptor | crispy}}
            
            <button type="submit" class="btn btn-success">Aceptar</button>
            <a href="{% url 'preceptores' %}" class="btn btn-danger">Cancelar</a>
        </form>

    </div>

{% endblock Contenido %}

Usuarios/templates/Usuarios/formProfesor.html
{% extends 'Usuarios/menuAdmin.html' %}

{% block Contenido %}

    {% load crispy_forms_tags %}
    
    <div class="container">

        <form method="POST" autocomplete="off">
            {% csrf_token %}
            
            {{frmUsuario | crispy}}
            {{formProfesor | crispy}}
            
            <button type="submit" class="btn btn-success">Aceptar</button>
            <a href="{% url 'profesores' %}" class="btn btn-danger">Cancelar</a>
        </form>

    </div>

{% endblock Contenido %}

Usuarios/templates/Usuarios/menuAdmin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Director General | {{titulo}}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'CFP/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'CFP/css/estilos.css' %}">

    <!--jquery-confirm css. Para crear alerts y confirm jquery con estilos css. Abajo está el js-->
    <!-- https://craftpip.github.io/jquery-confirm/ -->
    <link type="text/css" rel="stylesheet" href="{% static 'CFP/css/jquery-confirm.css' %}">

</head>
<body>
    <section class="container">
        <!--
            ----------------------------------------------------------------
                                    BARRA NAVEGACION
            ----------------------------------------------------------------
        -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'menu' %}">Director General</a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item dropdown">
                        <a class="nav-link" href="{% url 'centros' %}" id="navbarDropdownMenuLink">
                            Centros De Formacion
                        </a>
                        
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">
                            Cursos
                        </a>
                        <div class="dropdown-menu bg-dark">
                            <a class="dropdown-item text-white" href="{% url 'cursos' %}">Todos Los Cursos</a>
                            <a class="dropdown-item text-white" href="{% url 'cursosInfo' %}">Informe</a>
                        </div>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profesores' %}">
                            Profesores
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'preceptores' %}">
                            Preceptores
                        </a>
                    </li>
                    
                    {% comment %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">
                            Localidades - Sacar Esto
                        </a>
                        <div class="dropdown-menu bg-dark">
                            <a class="dropdown-item text-white" href="{% url 'localidadNueva' %}">Nueva Localidad</a>
                            <a class="dropdown-item text-white" href="{% url 'localidades' %}">Lista De Localidades</a>
                        </div>
                    </li>
                    {% endcomment %}

                    <li class="nav-item">
                        <a href="{% url 'adminInfoAlumnos' %}" class="nav-link">Alumnos</a>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link " href="{% url 'logout' %}">Cerrar Sesion</a>
                    </li>
                </ul>
            </div>
        </nav>
        <!--
            ----------------------------------------------------------------
                                    FIN BARRA NAVEGACION
            ----------------------------------------------------------------
        -->
        <p class="h3 text-center mt-2">{{titulo}}</p>
        {% block Contenido %}
            
        {% endblock Contenido %}
            

    </section>
    <!--Fin container-->

    <!--JS jQuery, Popper, Bootstrap-->
    <script src=" {% static 'CFP/js/jquery-3.6.0.min.js' %} "></script>
    <script src=" {% static 'CFP/js/popper.min.js' %} "></script>
    <script src=" {% static 'CFP/js/bootstrap.min.js' %} "></script>

    <!--plugin para alerts de javascript (jquery) con estilos css y funciones varias-->
    <script src="{% static 'CFP/js/jquery-confirm.js' %}"></script>

    
    {% block jquery %}
        
    {% endblock jquery %}
        
</body>
</html>

Usuarios/templates/Usuarios/menuPreceptor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CFP {{usuario.preceptor.cfp}} | {{usuario.username}} </title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'CFP/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'CFP/css/estilos.css' %}">

</head>
<body>
    <section class="container">

        {% comment %}
        ----------------------------------------------------------------
                                BARRA NAVEGACION
        ----------------------------------------------------------------
        {% endcomment %}
    
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'preLstCursos' %}">Director {{usuario.preceptor.cfp}} {{usuario.first_name}} {{usuario.last_name}} </a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'preLstCursos' %}" id="navbarDropdownMenuLink" >
                            Cursos
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'preLstAlu' %}" id="navbarDropdownMenuLink" >
                            Alumnos
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#" id="navbarDropdownMenuLink" >
                            Profesores
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link " href="{% url 'logout' %}">Cerrar Sesion</a>
                    </li>
                </ul>
            </div>
        </nav>
        {% comment %}
        ----------------------------------------------------------------
                                FIN BARRA NAVEGACION
        ----------------------------------------------------------------
        {% endcomment %}
        
        <p class="h3 text-center mt-2">{{titulo}}</p>

        {% block Contenido %}
            
        {% endblock Contenido %}
    </section>


    <!--JS jQuery, Popper, Bootstrap-->
    <script src=" {% static 'CFP/js/jquery-3.6.0.min.js' %} "></script>
    <script src=" {% static 'CFP/js/popper.min.js' %} "></script>
    <script src=" {% static 'CFP/js/bootstrap.min.js' %} "></script>

    {% block jquery %}
        
    {% endblock jquery %}

</body>
</html>